version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - APACHE_LOG_DIR=/var/log/apache2
    container_name: mi-proyecto-php
